global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['django:8000']
  - job_name: 'celery'
    static_configs:
      - targets: ['celery_worker']
  - job_name: 'kafka'
    static_configs:
      - targets: ['kafka:9092']