global:
  scrape_interval: 60s

scrape_configs:
  - job_name: 'django'
    static_configs:
      - targets: ['django:8000']
  - job_name: 'celery'
    static_configs:
      - targets: ['celery_worker']